import { buildWorld } from "@shared/simulation/season";
import { resolveYear } from "@shared/simulation/resolve";
import { defaultDraft } from "@shared/simulation/levers";
import { nicheById } from "@shared/simulation/niches";
import { ROLES, type TeamDecisions } from "@shared/simulation/types";
const held = (c: any) => Object.values(c?.customers ?? {}).reduce((s: number, n: any) => s + Number(n||0), 0);
const niche: any = nicheById("dating_apps")!;
const firstPeriod = (cities?: string[]) => {
  const world: any = buildWorld({ seasonId: "known-door", niche, cadence: "quarterly", teams: [{ id: "me", name: "Mine", seats: [...ROLES], officers: 1 }] });
  const me: any = world.companies.find((c: any) => c.id === "me")!;
  const filed: any = { companyId: "me" };
  for (const r of ROLES) filed[r] = { ...defaultDraft(r, me) };
  if (cities) filed.cmo = { ...filed.cmo, targetCities: [...me.cities, ...cities] };
  const out = resolveYear({ ...world, year: 1 }, [filed as TeamDecisions], undefined, { withoutEvent: true });
  const after: any = out.world.companies.find((c: any) => c.id === "me");
  const rep: any = out.reports.find((r: any) => r.companyId === "me");
  return { capacity: me.capacity, held: held(after), turnedAway: rep.turnedAway, cities: me.cities };
};
const home = firstPeriod();
const bought = [...niche.cities].filter((c: any) => !home.cities.includes(c.id)).sort((a: any,b: any)=>b.weight-a.weight)[0];
const wider = firstPeriod([bought.id]);
console.log("home  plant", home.capacity, "held", home.held, "turnedAway", home.turnedAway);
console.log("wider plant", wider.capacity, "held", wider.held, "turnedAway", wider.turnedAway);
console.log("plant full?", home.held >= home.capacity, wider.held >= wider.capacity);
