/**
 * The two background jobs backing depends on: sending merch, and not sitting
 * on money forever.
 *
 * Both take a Postgres advisory lock before doing anything, so running more
 * than one server process can't double-submit an order or double-refund a
 * pledge. The lock is released as soon as the pass finishes; if a process dies
 * holding it, Postgres drops it with the connection.
 */
import { and, eq, inArray, isNotNull, lt, sql } from "drizzle-orm";
import { db, pool } from "./db";
import {
  projectBackings, projectBackingCampaigns, projectMerchOrders, projects,
  type ShippingAddress, type MerchOrderItem,
} from "@shared/schema";
import { getUncachableStripeClient } from "./stripeClient";
import {
  createOrder, isPrintfulConfigured, PrintfulNotConfiguredError,
  type PrintfulOrderItem, type PrintfulRecipient,
} from "./printful";
import { type MerchConfig } from "@shared/backing";

/** Distinct ids so the two jobs never block each other. */
const LOCK_FULFILLMENT = 918_2701;
const LOCK_SWEEP = 918_2702;

async function withLock<T>(key: number, run: () => Promise<T>): Promise<T | null> {
  const client = await pool.connect();
  try {
    const { rows } = await client.query("SELECT pg_try_advisory_lock($1) AS ok", [key]);
    if (!rows[0]?.ok) return null; // Another process is already on it.
    try {
      return await run();
    } finally {
      await client.query("SELECT pg_advisory_unlock($1)", [key]);
    }
  } finally {
    client.release();
  }
}

// --- Artwork ------------------------------------------------------------

/**
 * Which Printful variant a product key prints on.
 *
 * Kept in the environment rather than in code because Printful's catalog ids
 * are theirs to change, and a wrong id silently prints the wrong garment.
 * Shape: PRINTFUL_VARIANT_MAP={"shirt":4012,"sticker_pack":10163}
 *
 * Populate it from GET /api/admin/printful/catalog.
 */
function variantMap(): Record<string, number> {
  try {
    const parsed = JSON.parse(process.env.PRINTFUL_VARIANT_MAP || "{}");
    return typeof parsed === "object" && parsed ? parsed : {};
  } catch {
    console.warn("[backing-jobs] PRINTFUL_VARIANT_MAP is not valid JSON — ignoring it.");
    return {};
  }
}

export class ArtworkUnavailableError extends Error {}

/**
 * Where Printful should fetch our print files from.
 *
 * Printful pulls the artwork over the public internet, so a local dev server
 * simply cannot fulfil — which is correct, and worth failing loudly about
 * rather than submitting an order pointing at localhost.
 */
function publicBaseUrl(): string {
  const raw = process.env.PUBLIC_URL || process.env.REPLIT_DOMAINS?.split(",")[0];
  if (!raw) {
    throw new ArtworkUnavailableError(
      "PUBLIC_URL is not set, so Printful has no address to fetch print files from.",
    );
  }
  return raw.startsWith("http") ? raw.replace(/\/$/, "") : `https://${raw}`;
}

/**
 * The print files for one order.
 *
 * These are URLs into our own renderer (`/api/merch-orders/:id/print/:face.png`),
 * which draws from the artwork snapshot stored on the order — so the file
 * Printful pulls is generated by the same code that drew the preview the
 * backer agreed to, from the config as it stood when they ordered.
 *
 * `backArtworkUrl` still wins when a creator has supplied finished art; they
 * know their brand better than a generic layout does.
 */
function resolvePrintFiles(config: MerchConfig, orderId: string): {
  files: { type: string; url: string }[];
} {
  const base = publicBaseUrl();
  const files = [
    { type: "front", url: `${base}/api/merch-orders/${orderId}/print/front.png` },
  ];

  if (config.backArtworkUrl) {
    files.push({ type: "back", url: config.backArtworkUrl });
  } else if (config.showLogo || config.showName || config.showDatestamp) {
    files.push({ type: "back", url: `${base}/api/merch-orders/${orderId}/print/back.png` });
  }

  return { files };
}

// --- Merch fulfillment --------------------------------------------------

/**
 * Sends queued merch for projects a reviewer has approved.
 *
 * Orders are created as Printful *drafts*. Nothing physically prints until
 * someone confirms it in the Printful dashboard — the correct posture until
 * the artwork pipeline has proved itself on real garments, because the failure
 * mode here costs money and gets posted to a stranger.
 */
export async function runMerchFulfillment(): Promise<{ submitted: number; failed: number } | null> {
  if (!isPrintfulConfigured()) return null;

  return withLock(LOCK_FULFILLMENT, async () => {
    const rows = await db.select({
      order: projectMerchOrders,
      campaign: projectBackingCampaigns,
      projectTitle: projects.title,
    }).from(projectMerchOrders)
      .innerJoin(projects, eq(projects.id, projectMerchOrders.projectId))
      .innerJoin(projectBackingCampaigns, eq(projectBackingCampaigns.projectId, projectMerchOrders.projectId))
      .where(and(
        eq(projectMerchOrders.status, "queued"),
        // The gate: a human said the project is real. Held here rather than on
        // the order row so approving a project frees its whole backlog.
        eq(projectBackingCampaigns.reviewStatus, "approved"),
      ))
      .limit(25);

    const map = variantMap();
    let submitted = 0;
    let failed = 0;

    for (const { order, campaign, projectTitle } of rows) {
      try {
        const address = order.shippingAddress as ShippingAddress | null;
        if (!address?.line1) throw new Error("No shipping address on this order.");

        const config = (campaign.merchConfig || {}) as MerchConfig;
        const { files } = resolvePrintFiles(config, order.id);

        const items: PrintfulOrderItem[] = (order.items as MerchOrderItem[]).map((item) => {
          const variantId = map[item.productKey];
          if (!variantId) {
            throw new Error(
              `"${item.productKey}" has no Printful variant. Add it to PRINTFUL_VARIANT_MAP.`,
            );
          }
          return { variant_id: variantId, quantity: item.quantity || 1, files };
        });

        const recipient: PrintfulRecipient = {
          name: address.name,
          address1: address.line1,
          address2: address.line2,
          city: address.city,
          state_code: address.state,
          country_code: address.country,
          zip: address.postalCode,
        };

        const created = await createOrder({
          externalId: order.id,
          recipient,
          items,
          confirm: process.env.PRINTFUL_AUTO_CONFIRM === "true",
        });

        await db.update(projectMerchOrders).set({
          status: "submitted",
          printfulOrderId: String(created.id),
          submittedAt: new Date(),
          lastError: null,
          updatedAt: new Date(),
        }).where(eq(projectMerchOrders.id, order.id));
        submitted++;
      } catch (err: any) {
        if (err instanceof PrintfulNotConfiguredError) break;
        // Stays queued: these are all fixable (map a variant, upload artwork)
        // and the next pass should retry rather than write the order off.
        await db.update(projectMerchOrders).set({
          lastError: String(err?.message || err).slice(0, 500),
          updatedAt: new Date(),
        }).where(eq(projectMerchOrders.id, order.id));
        failed++;
      }
    }

    if (submitted || failed) {
      console.log(`[merch] ${submitted} submitted, ${failed} still blocked`);
    }
    return { submitted, failed };
  });
}

// --- The refund window --------------------------------------------------

/**
 * Resolves pledges the creator never earned out.
 *
 * Only touches projects that have *not* been approved. An approved project
 * whose funds simply haven't been released yet is a reviewer's to-do, not a
 * backer's problem — refunding out from under it would punish the creator for
 * our own queue. Those stay held and stay visible in the payout console.
 *
 * Each backer chose at checkout what happens here, so this only carries out an
 * instruction that was already given.
 */
export async function runRefundSweep(): Promise<{ refunded: number; converted: number; failed: number } | null> {
  return withLock(LOCK_SWEEP, async () => {
    const rows = await db.select({
      backing: projectBackings,
      reviewStatus: projectBackingCampaigns.reviewStatus,
    }).from(projectBackings)
      .leftJoin(projectBackingCampaigns, eq(projectBackingCampaigns.projectId, projectBackings.projectId))
      .where(and(
        eq(projectBackings.status, "held"),
        isNotNull(projectBackings.refundDueAt),
        lt(projectBackings.refundDueAt, new Date()),
      ))
      .limit(50);

    const due = rows.filter((r) => r.reviewStatus !== "approved");
    if (due.length === 0) return { refunded: 0, converted: 0, failed: 0 };

    const stripe = await getUncachableStripeClient();
    let refunded = 0, converted = 0, failed = 0;

    for (const { backing } of due) {
      try {
        if (backing.unclaimedPreference === "donate_platform") {
          // The money is already in the platform balance — there is nothing to
          // move, only a status to settle.
          await db.update(projectBackings).set({
            status: "converted", resolvedAt: new Date(),
          }).where(eq(projectBackings.id, backing.id));
          converted++;
          continue;
        }

        if (!backing.stripePaymentIntentId) throw new Error("No payment intent to refund");
        const refund = await stripe.refunds.create({
          payment_intent: backing.stripePaymentIntentId,
          metadata: { backingId: backing.id, reason: "refund_window_elapsed" },
        }, { idempotencyKey: `sweep_refund_${backing.id}` });

        await db.update(projectBackings).set({
          status: "refunded",
          stripeRefundId: refund.id,
          resolvedAt: new Date(),
        }).where(eq(projectBackings.id, backing.id));

        // The public "raised" figure has to give the money back too.
        await db.update(projects)
          .set({ totalDonations: sql`greatest(0, ${projects.totalDonations} - ${backing.amountCents})` })
          .where(eq(projects.id, backing.projectId));

        // Nothing physical can have shipped — merch waits on approval and
        // these are unapproved by definition — so cancelling is safe.
        await db.update(projectMerchOrders)
          .set({ status: "canceled", updatedAt: new Date() })
          .where(and(
            eq(projectMerchOrders.backingId, backing.id),
            inArray(projectMerchOrders.status, ["queued", "failed"]),
          ));

        refunded++;
      } catch (err: any) {
        console.error(`[sweep] Backing ${backing.id} failed:`, err?.message || err);
        failed++;
      }
    }

    console.log(`[sweep] ${refunded} refunded, ${converted} converted, ${failed} failed`);
    return { refunded, converted, failed };
  });
}

/**
 * Starts both jobs on a timer.
 *
 * Intervals are generous on purpose: neither job is urgent, both take a lock,
 * and a tight loop against Stripe and Printful buys nothing.
 */
export function startBackingJobs(): void {
  const safely = (name: string, job: () => Promise<unknown>) => () => {
    job().catch((err) => console.error(`[backing-jobs] ${name} failed:`, err));
  };

  const fulfil = safely("fulfillment", runMerchFulfillment);
  const sweep = safely("sweep", runRefundSweep);

  // A few seconds after boot, so a restart picks up anything left behind
  // without competing with startup work.
  setTimeout(fulfil, 30_000);
  setTimeout(sweep, 60_000);

  setInterval(fulfil, 10 * 60_000).unref();
  setInterval(sweep, 60 * 60_000).unref();
}
