/**
 * The markets a team can enter.
 *
 * Each one is a different shape of problem rather than a different noun: the
 * incumbents' postures, how loyal the segments are and how fast quality moves
 * decide what winning looks like. A niche where everybody is loyal and quality
 * moves slowly is a grinding brand war; one with a flighty segment and a fast
 * pace can be cracked in three years by a team that reads it.
 *
 * ## Every market is roughly the same size, and that is not decoration
 *
 * Each of these totals somewhere between three and four hundred million a year
 * at the reference prices. That is a hard constraint the engine imposes, and
 * breaking it quietly breaks the game.
 *
 * A company here pays around 1.1m a year in fixed costs before anybody decides
 * anything, and moving brand or quality at all costs a few hundred thousand,
 * because that is where `lift`'s half-saturation sits. A market worth 15m a
 * year cannot support a company with those costs: every team in it goes
 * bankrupt in year one whatever they do, and the season stops being a game and
 * becomes arithmetic. That is exactly what happened when these markets were
 * first written an order of magnitude too small, and it took running a full
 * fourteen-year season to notice.
 *
 * So when adding one: multiply each segment's size by its reference price, add
 * them up, and land near 350m. `test/unit/balance.test.ts` then plays it for a
 * whole season with four different strategies and will say so if the result is
 * unwinnable, a walkover, or rewards exactly what every other market rewards.
 *
 * ## Loyalty is the dial that decides how a market plays
 *
 * Whether customers stay is what makes one of these a knife fight and another
 * a decade-long siege. A flighty segment is the door a newcomer comes through;
 * a loyal one is what makes the fortnight's work worth something afterwards.
 * Every market here has at least one of each, because a market of only loyal
 * customers cannot be entered and a market of only flighty ones cannot be held.
 */
import type { Niche } from "./types";

export const NICHES: Niche[] = [
  {
    id: "dating_apps",
    worldHome: "uk_ireland",
    // Everyone dates; not everyone pays an app to help.
    penetration: { africa: 0.6, asia: 0.85 },
    name: "Dating apps",
    premise: "Everybody has an opinion and nobody admits to paying. Your best customers leave the moment you succeed.",
    baseUnitCost: 6,
    innovationPace: 1.2,
        workforce: [
      { id: "moderators", name: "moderators", one: "a moderator", does: "service", pay: 0.75, share: 0.4 },
      { id: "engineers", name: "engineers", one: "an engineer", does: "product", pay: 1.6, share: 0.4 },
      { id: "community", name: "community managers", one: "a community manager", does: "room", pay: 0.9, share: 0.2 },
    ],
    voice: {
      customer: "subscriber",
      customers: "subscribers",
      unit: "a month of premium",
      per: "a month",
      capacity: "how many people you can match well on a Friday night before the whole thing starts to feel empty",
      capacityShort: "subscribers you can carry",
      place: "city",
      places: "cities",
      quality: "whether the matches are any good",
      brand: "whether anyone has heard of you",
      service: "moderation, safety, and whether a human ever replies",
      turnedAway: "people who opened the app, found nobody nearby, and did not open it again",
      market: "the dating market",
      rivals: "the other apps",
    },
    segments: [
      { id: "swipers", name: "Swipers", description: "On three apps at once, delete them all on a Sunday night, reinstall by Wednesday.", size: 4_440_000, growth: 0.03, priceSensitivity: 0.8, qualityFocus: 0.3, brandFocus: 0.62, serviceFocus: 0.2, loyalty: 0.15, referencePrice: 40 },
      { id: "recently_single", name: "The recently single", description: "Arrive raw and generous, download everything, and are gone within six months either way.", size: 1_560_000, growth: 0.06, priceSensitivity: 0.45, qualityFocus: 0.55, brandFocus: 0.4, serviceFocus: 0.45, loyalty: 0.22, referencePrice: 70 },
      { id: "long_haulers", name: "The long-haulers", description: "Four years on premium. Blame the algorithm, never the app.", size: 720_000, growth: 0.04, priceSensitivity: 0.25, qualityFocus: 0.75, brandFocus: 0.28, serviceFocus: 0.62, loyalty: 0.86, referencePrice: 160 },
    ],
    cities: [
      { id: "london", name: "London", weight: 0.279, entryCost: 1_300_000, note: "Density is the product here, and everybody already has it.",
        mix: { swipers: 1, recently_single: 1, long_haulers: 1 } },
      { id: "manchester", name: "Manchester", weight: 0.153, entryCost: 500_000, note: "Big enough that the app feels alive on a Friday night.",
        mix: { swipers: 1.067, recently_single: 1.0, long_haulers: 0.955 } },
      { id: "birmingham", name: "Birmingham", weight: 0.135, entryCost: 460_000, note: "Underserved, and nobody has made it feel local yet.",
        mix: { swipers: 1.0, recently_single: 1.022, long_haulers: 0.978 } },
      { id: "glasgow", name: "Glasgow", weight: 0.126, entryCost: 420_000, note: "Word of mouth travels faster here than any advert.",
        mix: { swipers: 0.978, recently_single: 1.0, long_haulers: 1.045 } },
      { id: "bristol", name: "Bristol", weight: 0.117, entryCost: 400_000, note: "Young, online, and quick to try whatever is new.",
        mix: { swipers: 1.045, recently_single: 1.022, long_haulers: 0.955 } },
      { id: "leeds", name: "Leeds", weight: 0.09, entryCost: 320_000, note: "The cheapest place to find out whether the thing works at all.",
        mix: { swipers: 1.022, recently_single: 1.0, long_haulers: 0.978 } },
      { id: "liverpool", name: "Liverpool", weight: 0.035, entryCost: 110_000, note: "Nights out start early and end late, and everyone knows everyone.",
        mix: { swipers: 1.067, recently_single: 1.0, long_haulers: 0.932 } },
      { id: "newcastle", name: "Newcastle", weight: 0.03, entryCost: 90_000, note: "Fiercely local. An app that feels national gets ignored here.",
        mix: { swipers: 1.0, recently_single: 0.978, long_haulers: 1.045 } },
      { id: "edinburgh", name: "Edinburgh", weight: 0.02, entryCost: 60_000, note: "Older, settled, and the least interested in swiping anywhere.",
        mix: { swipers: 0.932, recently_single: 1.022, long_haulers: 1.09 } },
      { id: "nottingham", name: "Nottingham", weight: 0.015, entryCost: 50_000, note: "Two universities and a short memory. Cheap, fast, and fickle.",
        mix: { swipers: 1.09, recently_single: 1.0, long_haulers: 0.91 } },
    ],
    incumbents: [
      {
        id: "inc_ember", name: "Ember", posture: "fortress", startingShare: 0.39, quality: 66, brand: 88, service: 58, priceIndex: 1.18,
        persona: {
          tagline: "Where it starts.",
          boss: "Marguerite Vale, who has run it for nine years and describes it in interviews as infrastructure rather than an app.",
          character: "Ember is not the best dating app and has not needed to be since 2019. It is the one your mum has heard of, the one on the bus stop, the one you download last after the others have disappointed you. It spends enormous sums on trust and safety and almost nothing on being fun, because its research says people forgive a boring app and never forgive a frightening one. It would rather lose a million swipers than one headline.",
          known: "Everybody has heard of it",
          knock: "The app has barely changed in four years. Everybody is on it and nobody likes it, which is a position you can hold for a decade and lose in eighteen months.",
          voice: "We welcome new entrants to the category. Most of them are very good at growth and very bad at the parts that matter.",
        },
      },
      {
        id: "inc_pairwise", name: "Pairwise", posture: "brawler", startingShare: 0.24, quality: 57, brand: 71, service: 46, priceIndex: 0.78,
        persona: {
          tagline: "Half the price. Twice the dates.",
          boss: "Dez Okonkwo, a growth marketer who took over from the founders and put a discount banner on the login screen within a week.",
          character: "Pairwise competes on price and will keep competing on price long after it stops making sense. Every quarter there is a new offer, every offer trains its users to wait for the next one, and the whole company now runs on a treadmill it built itself. It is genuinely good at acquisition and genuinely bad at anyone staying.",
          known: "Nobody undercuts them",
          knock: "A third of the profiles have not been opened in a year. The number on the homepage counts accounts, not people, and everyone in the industry knows it.",
          voice: "Charge what you like. We will be cheaper on Monday.",
        },
      },
      {
        id: "inc_spark", name: "Spark", posture: "coaster", startingShare: 0.17, quality: 45, brand: 69, service: 38, priceIndex: 0.96,
        persona: {
          tagline: "The original.",
          boss: "Nobody, really. It reports into a holding company two floors up and has had four interim heads in three years.",
          character: "Spark was the app in 2014 and has been quietly living off that ever since. The roadmap is maintenance, the support queue is a chatbot, and the brand still buys it more goodwill than the product has earned in a decade. It is not badly run so much as not run at all — a large, warm, slowly deflating thing that nobody has decided what to do with.",
          known: "A name people still recognise",
          knock: "Nobody is driving. It survives on habit, and habit is the one asset a better product takes without a fight.",
          voice: "We have been here a long time. We expect to be here a while yet.",
        },
      },
      {
        id: "inc_lantern", name: "Lantern", posture: "innovator", startingShare: 0.1, quality: 83, brand: 52, service: 67, priceIndex: 1.32,
        persona: {
          tagline: "Fewer matches. Better ones.",
          boss: "Dr Ines Halvorsen, a behavioural scientist who says the word intentional more often than is strictly necessary.",
          character: "Lantern shows you six people a day and makes you write to them properly. It is, measurably, the best product in the market — the long-haulers who find it never leave — and it is priced like a gym membership because the economics do not work any other way. Everyone who uses it loves it. That is nine people out of a hundred.",
          known: "The best matches in the market",
          knock: "Almost nobody has heard of it, and it costs more than the other three combined. A well-funded newcomer could buy the awareness it has spent six years not buying.",
          voice: "We are not trying to be the biggest. We would, however, quite like to be told when somebody copies us.",
        },
      },
    ],
  },
  {
    id: "drone_delivery",
    worldHome: "uk_ireland",
    /* You cannot fly a parcel to somewhere with no address and no air traffic control. */
    penetration: { africa: 0.25, south_america: 0.7, middle_east: 0.8, oceania: 0.6, asia: 0.9 },
    name: "Drone delivery",
    premise: "Ten minutes from warehouse to doorstep, if the weather holds and the regulator is in a good mood. Half the cost is the drone; the other half is explaining it to the neighbours.",
    baseUnitCost: 10,
    innovationPace: 0.9,
        workforce: [
      { id: "pilots", name: "pilots", one: "a pilot", does: "room", pay: 1.0, share: 0.5 },
      { id: "mechanics", name: "mechanics", one: "a mechanic", does: "product", pay: 1.1, share: 0.25 },
      { id: "dispatch", name: "dispatchers", one: "a dispatcher", does: "service", pay: 0.8, share: 0.25 },
    ],
    voice: {
      customer: "customer",
      customers: "customers",
      unit: "a delivery",
      per: "a drop",
      capacity: "how many drops you can fly in a day, once the weather and the airspace have had their say",
      capacityShort: "customers you can fly for",
      place: "region",
      places: "regions",
      quality: "whether it lands on time and in one piece",
      brand: "whether anyone has heard of you when the leaflet comes through the door",
      service: "what happens the day a drop goes missing",
      turnedAway: "orders refused because there was no airframe free",
      market: "the delivery market",
      rivals: "the other operators",
    },
    segments: [
      { id: "novelty", name: "Novelty orderers", description: "Order once to watch it land, film it, and never think about it again.", size: 2_440_000, growth: 0.02, priceSensitivity: 0.75, qualityFocus: 0.3, brandFocus: 0.6, serviceFocus: 0.25, loyalty: 0.12, referencePrice: 25 },
      { id: "rural", name: "Rural households", description: "Forty minutes from the nearest shop. Once you're the only one who reaches them, you're theirs until somebody else does.", size: 1_220_000, growth: 0.07, priceSensitivity: 0.35, qualityFocus: 0.6, brandFocus: 0.25, serviceFocus: 0.85, loyalty: 0.8, referencePrice: 150 },
      { id: "clinics", name: "Pharmacies and clinics", description: "Prescriptions, samples, things that can't wait. A year of paperwork to sign, and they never switch a supplier that hasn't dropped anything.", size: 200_000, growth: 0.09, priceSensitivity: 0.2, qualityFocus: 0.85, brandFocus: 0.3, serviceFocus: 0.95, loyalty: 0.9, referencePrice: 700 },
    ],
    cities: [
      { id: "south_east", name: "The South East", weight: 0.261, entryCost: 1_500_000, note: "Dense, wealthy, and the strictest airspace in the country.",
        mix: { novelty: 1, rural: 1, clinics: 1 } },
      { id: "midlands", name: "The Midlands", weight: 0.18, entryCost: 620_000, note: "Warehouses everywhere, and short hops between them.",
        mix: { novelty: 1.022, rural: 0.978, clinics: 1.0 } },
      { id: "north_west", name: "The North West", weight: 0.153, entryCost: 540_000, note: "The weather costs you a dozen days a year, every year.",
        mix: { novelty: 1.0, rural: 1.022, clinics: 0.978 } },
      { id: "scotland", name: "Scotland", weight: 0.135, entryCost: 480_000, note: "The distances that make this expensive are the ones that make it worth doing.",
        mix: { novelty: 0.91, rural: 1.135, clinics: 0.978 } },
      { id: "south_west", name: "The South West", weight: 0.099, entryCost: 380_000, note: "Scattered villages, and nobody else bothering with them.",
        mix: { novelty: 0.932, rural: 1.113, clinics: 0.955 } },
      { id: "wales", name: "Wales", weight: 0.072, entryCost: 300_000, note: "Cheapest licence in the country, and the hardest terrain to fly.",
        mix: { novelty: 0.91, rural: 1.135, clinics: 0.932 } },
      { id: "yorkshire", name: "Yorkshire", weight: 0.035, entryCost: 120_000, note: "Moorland between market towns: long legs, few landing spots.",
        mix: { novelty: 0.955, rural: 1.09, clinics: 0.978 } },
      { id: "east_anglia", name: "East Anglia", weight: 0.03, entryCost: 100_000, note: "Flat, quiet airspace and farms that order by the pallet.",
        mix: { novelty: 0.932, rural: 1.113, clinics: 0.978 } },
      { id: "north_east", name: "The North East", weight: 0.02, entryCost: 70_000, note: "Small, cheap, and three hospitals that would sign tomorrow.",
        mix: { novelty: 0.955, rural: 1.022, clinics: 1.113 } },
      { id: "northern_ireland", name: "Northern Ireland", weight: 0.015, entryCost: 50_000, note: "Its own regulator, and clinics that have been asking for years.",
        mix: { novelty: 0.932, rural: 1.045, clinics: 1.113 } },
    ],
    incumbents: [
      {
        id: "inc_skyhop", name: "Skyhop", posture: "fortress", startingShare: 0.36, quality: 71, brand: 80, service: 74, priceIndex: 1.16,
        persona: {
          tagline: "Cleared for landing since 2019.",
          boss: "Group Captain (ret.) Alan Pryce, who runs a delivery company the way he ran a squadron, which is most of why it works.",
          character: "Skyhop got its licences first and has spent every year since making sure nobody else gets theirs easily. It has more lawyers than pilots, an incident record it will show you unprompted, and a genuine, slightly boring excellence at the parts of this that are not flying. When something goes wrong a person telephones you. That is the entire moat.",
          known: "The regulator takes their calls",
          knock: "Everything takes them a year. A rival can be in three regions before Skyhop has finished the paperwork for one.",
          voice: "Flying is the easy part. We look forward to reading their incident reports.",
        },
      },
      {
        id: "inc_dropzone", name: "Dropzone", posture: "brawler", startingShare: 0.28, quality: 55, brand: 64, service: 47, priceIndex: 0.76,
        persona: {
          tagline: "Cheaper than a van. Faster than a van.",
          boss: "Kayleigh Brandt, who came from parcel logistics and has never once been heard to use the word airspace.",
          character: "Dropzone treats a drone as a van that does not need a driver, and prices accordingly. It runs the oldest fleet in the market at the highest utilisation and undercuts anybody who moves into its patch, including at a loss, on the theory that the loss is temporary and the customer is not. Its maintenance intervals are a subject nobody there enjoys discussing.",
          known: "The cheapest drop in the country",
          knock: "They lose things. Not often enough to be a scandal, often enough that no clinic will sign with them.",
          voice: "Whatever they quoted you, take ten per cent off and it is ours.",
        },
      },
      {
        id: "inc_hummingbird", name: "Hummingbird", posture: "innovator", startingShare: 0.15, quality: 86, brand: 53, service: 68, priceIndex: 1.34,
        persona: {
          tagline: "Anything, anywhere, intact.",
          boss: "Wei Tanaka, an aerospace engineer who left a very large company because they would not let her fly in rain.",
          character: "Hummingbird builds its own airframes and they are markedly better than anybody else\u2019s: quieter, steadier, and able to fly on days the rest of the fleet is grounded. Everything is spent on the next airframe, which means the price is high, the marketing is a slide deck, and the sales team is four people. The clinics that have tried them will not go back.",
          known: "Flies in weather nobody else will",
          knock: "They are an engineering company that happens to sell deliveries. Two thirds of the market has never heard the name.",
          voice: "They are welcome to the novelty orders. We will take the ones that matter.",
        },
      },
      {
        id: "inc_kestrel", name: "Kestrel", posture: "coaster", startingShare: 0.11, quality: 48, brand: 57, service: 43, priceIndex: 0.98,
        persona: {
          tagline: "Reliable regional delivery.",
          boss: "A regional director who is eighteen months from retirement and has said so in a meeting.",
          character: "Kestrel was an early mover, took a large early contract, and has been executing that one contract ever since. The fleet is adequate, the routes have not been re-planned in four years, and the whole operation is pointed at renewal rather than growth. It is profitable, becalmed, and entirely uninterested in a fight.",
          known: "One very large contract",
          knock: "Everything outside that contract is unattended. Whole regions are theirs on paper and nobody there has visited.",
          voice: "Good luck to them. We have a route to run.",
        },
      },
    ],
  },
  {
    id: "podcasts",
    /* Already continental: it widens straight onto the map. */
    penetration: { north_america: 1.4, europe: 1.1, asia: 0.7, africa: 0.5 },
    name: "Podcasts",
    premise: "Free to start, free to listen, and the same twenty shows have sat at the top of the chart for five years. Listeners don't pay you; advertisers pay you to talk about mattresses.",
    baseUnitCost: 2,
    innovationPace: 1.35,
        workforce: [
      { id: "producers", name: "producers", one: "a producer", does: "product", pay: 1.1, share: 0.4 },
      { id: "editors", name: "editors", one: "an editor", does: "room", pay: 0.85, share: 0.4 },
      { id: "ad_ops", name: "ad sales", one: "an ad seller", does: "service", pay: 0.95, share: 0.2 },
    ],
    voice: {
      customer: "listener",
      customers: "listeners",
      unit: "a thousand downloads sold to an advertiser",
      per: "a thousand downloads",
      capacity: "how many shows you can make properly at once, before the good ones start sounding rushed",
      capacityShort: "listeners you can serve",
      place: "market",
      places: "markets",
      quality: "whether people finish the episode",
      brand: "whether you are in the chart people actually look at",
      service: "how you treat hosts, guests, and the brands paying for the ad reads",
      turnedAway: "advertisers you had nothing left to sell",
      market: "the podcast business",
      rivals: "the other networks",
    },
    segments: [
      { id: "chart_hoppers", name: "Chart-hoppers", description: "Listen to whatever's number one, skip the ads, forget the host's name.", size: 10_000_000, growth: 0.05, priceSensitivity: 0.85, qualityFocus: 0.35, brandFocus: 0.7, serviceFocus: 0.15, loyalty: 0.14, referencePrice: 14 },
      { id: "commuters", name: "Commute regulars", description: "Every weekday, same slot, same voices. Will stay through a bad year but not through a co-host leaving.", size: 3_560_000, growth: 0.06, priceSensitivity: 0.4, qualityFocus: 0.7, brandFocus: 0.45, serviceFocus: 0.4, loyalty: 0.74, referencePrice: 38 },
      { id: "superfans", name: "Superfans", description: "Pay for the bonus feed, wear the merch, know the dog's name. A few thousand of them are worth more than a million of the others.", size: 270_000, growth: 0.1, priceSensitivity: 0.15, qualityFocus: 0.8, brandFocus: 0.3, serviceFocus: 0.9, loyalty: 0.9, referencePrice: 380 },
    ],
    cities: [
      { id: "north_america", name: "North America", weight: 0.297, entryCost: 1_600_000, note: "Six times the money and thirty times the competition.",
        mix: { chart_hoppers: 1, commuters: 1, superfans: 1 } },
      { id: "uk", name: "The UK", weight: 0.234, entryCost: 700_000, note: "Where you start, and where the advertisers already know your name.",
        mix: { chart_hoppers: 1.022, commuters: 1.067, superfans: 0.978 } },
      { id: "australia", name: "Australia and New Zealand", weight: 0.117, entryCost: 450_000, note: "Small, loyal, and pays close to American rates.",
        mix: { chart_hoppers: 0.955, commuters: 1.045, superfans: 1.067 } },
      { id: "south_africa", name: "South Africa", weight: 0.09, entryCost: 340_000, note: "Growing fast, and almost nobody selling advertising into it.",
        mix: { chart_hoppers: 1.022, commuters: 1.0, superfans: 0.978 } },
      { id: "india", name: "India", weight: 0.09, entryCost: 380_000, note: "An enormous audience at a fraction of the advertising rate.",
        mix: { chart_hoppers: 1.113, commuters: 1.0, superfans: 0.91 } },
      { id: "ireland", name: "Ireland", weight: 0.072, entryCost: 260_000, note: "Cheap to enter, and a chart you can actually reach the top of.",
        mix: { chart_hoppers: 1.0, commuters: 1.022, superfans: 1.045 } },
      { id: "nordics", name: "The Nordics", weight: 0.035, entryCost: 120_000, note: "The longest commutes in Europe, and headphones on all of them.",
        mix: { chart_hoppers: 0.932, commuters: 1.135, superfans: 1.022 } },
      { id: "germany", name: "Germany", weight: 0.03, entryCost: 100_000, note: "Pays properly, listens in German, and will not take a translation.",
        mix: { chart_hoppers: 0.955, commuters: 1.09, superfans: 1.022 } },
      { id: "brazil", name: "Brazil", weight: 0.02, entryCost: 70_000, note: "Enormous, mobile, and almost entirely untouched by ad money.",
        mix: { chart_hoppers: 1.135, commuters: 0.978, superfans: 0.932 } },
      { id: "philippines", name: "The Philippines", weight: 0.015, entryCost: 50_000, note: "English-speaking, phone-first, and the cheapest audience anywhere.",
        mix: { chart_hoppers: 1.113, commuters: 1.0, superfans: 0.932 } },
    ],
    incumbents: [
      {
        id: "inc_daily_brief", name: "The Daily Brief", posture: "fortress", startingShare: 0.33, quality: 74, brand: 87, service: 55, priceIndex: 1.14,
        persona: {
          tagline: "Twenty minutes. Every morning. Since 2016.",
          boss: "Editor-in-chief Ruth Adeyemi, who came from newspapers and still runs it like a newsroom with a six a.m. deadline.",
          character: "The Daily Brief is a habit rather than a show. Four million people have listened to it at the same point in their morning for years, which makes it the single most valuable slot in the business and almost impossible to attack directly. It reinvests in the newsroom, not in being liked, and treats its hosts as staff — which is both why it is consistent and why it keeps losing them.",
          known: "The morning slot, owned outright",
          knock: "Their talent leaves. Every eighteen months somebody good walks out and takes a chunk of the audience with them, and the network has never worked out how to stop it.",
          voice: "Charts move. Routines do not.",
        },
      },
      {
        id: "inc_two_guys", name: "Two Guys Talking", posture: "coaster", startingShare: 0.27, quality: 44, brand: 76, service: 33, priceIndex: 0.92,
        persona: {
          tagline: "You know the one.",
          boss: "The two guys. They have an agent now and have not been in the same room since March.",
          character: "Two Guys Talking has been in the top five for six years on the strength of being on in the background. The episodes are long, unedited and increasingly recorded separately; the ad reads are done badly and on purpose, which the audience finds charming and the advertisers do not. Nobody is making it better because nobody has had to.",
          known: "An audience that will not leave",
          knock: "It is coasting and you can hear it. The chart-hoppers are still there out of habit and would go tomorrow for something that sounded like anybody cared.",
          voice: "Mate, we do not even know what our numbers are.",
        },
      },
      {
        id: "inc_echo", name: "Echo Media", posture: "brawler", startingShare: 0.18, quality: 59, brand: 62, service: 48, priceIndex: 0.74,
        persona: {
          tagline: "More shows. Lower rates.",
          boss: "Marco Feld, who buys shows the way other people buy shares and has never listened to one of them all the way through.",
          character: "Echo owns eighty shows and commissions another thirty a year, most of which fail, which is the plan. It undercuts every rate card in the market and makes it back on volume, and it treats hosts as replaceable because at that volume they are. The good shows on its roster are good by accident and are usually poached within two years.",
          known: "Nobody can match their rates",
          knock: "Their hosts hate them. A network that treats talent well can take Echo\u2019s three best shows in a single season.",
          voice: "Every show has a price. Yours included.",
        },
      },
      {
        id: "inc_nightcap", name: "Nightcap", posture: "innovator", startingShare: 0.12, quality: 85, brand: 51, service: 70, priceIndex: 1.3,
        persona: {
          tagline: "Made like it matters.",
          boss: "Sol Ferreira, a former radio documentary producer who will delay a season by a month over a bad edit and has done, twice.",
          character: "Nightcap makes eight shows a year and every one of them is extraordinary: scored, sound-designed, and researched for a year before anybody records anything. The superfans it collects pay for bonus feeds, live shows and merchandise at rates the rest of the market cannot imagine. It costs a fortune to make and it has never once been in a chart.",
          known: "The most devoted audience in the business",
          knock: "Eight shows a year is not a business, it is a portfolio. They have no answer at all to somebody who makes work nearly as good, four times as often.",
          voice: "We are quite pleased people are finally taking the craft seriously.",
        },
      },
    ],
  },
  {
    id: "restaurant_chain",
    worldHome: "uk_ireland",
    // People eat out everywhere. What they will pay for it is already in the map.
    penetration: { africa: 0.7 },
    name: "Restaurant chain",
    premise: "Same menu in forty towns. The food is the easy part; the hard part is finding four hundred people who'll show up on a Saturday to cook it.",
    baseUnitCost: 6,
    innovationPace: 0.5,
        workforce: [
      { id: "kitchen", name: "chefs and kitchen staff", one: "a chef", does: "room", pay: 0.7, share: 0.5 },
      { id: "front", name: "front of house", one: "a server", does: "service", pay: 0.6, share: 0.35 },
      { id: "managers", name: "area managers", one: "an area manager", does: "product", pay: 1.4, share: 0.15 },
    ],
    voice: {
      customer: "diner",
      customers: "diners",
      unit: "a cover",
      per: "a head",
      capacity: "how many covers you can actually serve, which is a staffing problem long before it is a building problem",
      capacityShort: "diners you can seat",
      place: "region",
      places: "regions",
      quality: "the food, and whether it is the same in all forty kitchens",
      brand: "whether anyone says your name when somebody asks where we should eat",
      service: "the wait, the welcome, and what happens when something is wrong",
      turnedAway: "people who looked at the queue and went somewhere else",
      market: "the high street",
      rivals: "the other chains",
    },
    segments: [
      { id: "lunch", name: "Lunch crowd", description: "Twelve minutes, under fifteen pounds, gone. Will switch for a shorter queue or a coupon.", size: 13_330_000, growth: 0.03, priceSensitivity: 0.85, qualityFocus: 0.35, brandFocus: 0.35, serviceFocus: 0.5, loyalty: 0.18, referencePrice: 13 },
      { id: "families", name: "Friday families", description: "Need a high chair, a kids' menu, and no surprises. Once you are the place, you are the place for a decade.", size: 3_330_000, growth: 0.05, priceSensitivity: 0.45, qualityFocus: 0.65, brandFocus: 0.45, serviceFocus: 0.8, loyalty: 0.82, referencePrice: 42 },
      { id: "delivery", name: "Delivery-app orderers", description: "Have never seen your building. Loyal to the app, not to you, and the app takes thirty per cent for the introduction.", size: 5_560_000, growth: 0.09, priceSensitivity: 0.7, qualityFocus: 0.5, brandFocus: 0.3, serviceFocus: 0.45, loyalty: 0.16, referencePrice: 22 },
    ],
    cities: [
      { id: "london", name: "London", weight: 0.252, entryCost: 1_700_000, note: "The rent is the business plan. Everything else is detail.",
        mix: { lunch: 1, families: 1, delivery: 1 } },
      { id: "north_west", name: "The North West", weight: 0.171, entryCost: 620_000, note: "Forty towns within an hour of each other. Made for a chain.",
        mix: { lunch: 1.0, families: 1.045, delivery: 1.0 } },
      { id: "midlands", name: "The Midlands", weight: 0.162, entryCost: 580_000, note: "Nobody has owned this properly since the nineties.",
        mix: { lunch: 1.0, families: 1.045, delivery: 1.0 } },
      { id: "yorkshire", name: "Yorkshire", weight: 0.135, entryCost: 470_000, note: "Loyal once you have earned it, and slow to give it.",
        mix: { lunch: 0.978, families: 1.09, delivery: 0.955 } },
      { id: "scotland", name: "Scotland", weight: 0.108, entryCost: 420_000, note: "Staffing is the whole problem here, not footfall.",
        mix: { lunch: 1.0, families: 1.022, delivery: 1.0 } },
      { id: "south_west", name: "The South West", weight: 0.072, entryCost: 300_000, note: "Cheapest doors in the country, and three good months of trade.",
        mix: { lunch: 0.955, families: 1.113, delivery: 0.932 } },
      { id: "east_anglia", name: "East Anglia", weight: 0.035, entryCost: 120_000, note: "Market towns and retail parks: families park, eat, and go home.",
        mix: { lunch: 0.932, families: 1.135, delivery: 0.932 } },
      { id: "wales", name: "Wales", weight: 0.03, entryCost: 100_000, note: "Small towns, long memories, and rent you can actually afford.",
        mix: { lunch: 0.955, families: 1.09, delivery: 0.955 } },
      { id: "north_east", name: "The North East", weight: 0.02, entryCost: 70_000, note: "Value is the whole conversation, and delivery is how it arrives.",
        mix: { lunch: 0.978, families: 1.022, delivery: 1.09 } },
      { id: "northern_ireland", name: "Northern Ireland", weight: 0.015, entryCost: 50_000, note: "A short hop and a separate supply chain to get anything there.",
        mix: { lunch: 0.978, families: 1.067, delivery: 0.978 } },
    ],
    incumbents: [
      {
        id: "inc_burger_barn", name: "Burger Barn", posture: "brawler", startingShare: 0.38, quality: 48, brand: 85, service: 44, priceIndex: 0.72,
        persona: {
          tagline: "Two for a tenner. Always.",
          boss: "Group CEO Phil Mather, who has done the same interview about value for eleven years and means every word of it.",
          character: "Burger Barn has four hundred sites, a menu unchanged since 2011, and the cheapest plate of food on any high street in the country. It is not good and it has never pretended to be; it is there, it is open, it is eight pounds, and on a wet Tuesday that beats good. The moment anybody prices near it, it goes lower, and it can afford to for longer than you can.",
          known: "Nobody is cheaper",
          knock: "Nobody chooses it, they settle for it. Every family that finds somewhere decent at forty pounds never comes back, and the families are where the money is.",
          voice: "Lovely menu. What is it, eighteen quid? We will see you in a year.",
        },
      },
      {
        id: "inc_fresco", name: "Fresco", posture: "fortress", startingShare: 0.25, quality: 69, brand: 76, service: 71, priceIndex: 1.2,
        persona: {
          tagline: "Sunday lunch, seven days a week.",
          boss: "Managing director Clare Nkemdirim, who still visits four sites a week unannounced and is not popular for it.",
          character: "Fresco is where families go, and has been for two decades. High chairs, a proper kids\u2019 menu, staff who have been there years, and a reliability that costs it a fortune in wages and earns it the most loyal customers in the trade. It will not discount, ever, on the grounds that a family who came for a coupon is not a family who is coming back.",
          known: "Friday families will not leave",
          knock: "It is expensive and slow, and it has no answer at all to the lunch crowd or to delivery. Two thirds of the market walks past it every day.",
          voice: "We have no view on discounting. We have never needed one.",
        },
      },
      {
        id: "inc_noodle_house", name: "Noodle House", posture: "innovator", startingShare: 0.16, quality: 82, brand: 54, service: 63, priceIndex: 1.28,
        persona: {
          tagline: "Open kitchen. Nothing to hide.",
          boss: "Chef-founder Ren Duthie, who still writes every menu and has turned down three private-equity approaches in public.",
          character: "Noodle House is the best food on this list by a distance and the hardest to scale, which is the entire story. Every site needs a chef who can actually cook, the menu changes four times a year, and the queues at the good ones go round the block. Growth is limited by the number of people alive who can run one properly.",
          known: "The best food on the high street",
          knock: "Sixteen sites in nine years. They cannot open fast enough to matter, and they know it.",
          voice: "Anyone can open forty rooms. Try staffing them.",
        },
      },
      {
        id: "inc_southside", name: "Southside Grill", posture: "coaster", startingShare: 0.11, quality: 46, brand: 58, service: 41, priceIndex: 0.97,
        persona: {
          tagline: "A proper grill house.",
          boss: "Owned by a pension fund. The operations director changes about every fourteen months.",
          character: "Southside had a very good decade and then stopped. The sites are tired, the refurbishment budget gets deferred every year, and the menu is priced in the middle of a market that has stopped rewarding the middle. It still trades, on car parks and location and nothing else, and everyone in the trade is waiting to see who buys the leases.",
          known: "Sites in places people drive to",
          knock: "Mid-priced and mid-quality in a trade that punishes both. Anybody better at forty pounds or cheaper at fifteen takes their customers without trying.",
          voice: "There is room for everyone on the high street.",
        },
      },
    ],
  },
  {
    id: "construction",
    worldHome: "uk_ireland",
    /* Building happens fastest where the people are arriving, not where the money already is. */
    penetration: { africa: 1.3, asia: 1.2, oceania: 0.8 },
    name: "Construction",
    premise: "Bid low, build slow, get paid late. Every job is a one-off, and every reputation is one bad roof from over.",
    baseUnitCost: 340,
    innovationPace: 0.45,
        workforce: [
      { id: "site", name: "site crews", one: "a site worker", does: "room", pay: 0.95, share: 0.55 },
      { id: "engineers", name: "structural engineers", one: "an engineer", does: "product", pay: 1.7, share: 0.25 },
      { id: "qs", name: "quantity surveyors", one: "a surveyor", does: "service", pay: 1.3, share: 0.2 },
    ],
    voice: {
      customer: "client",
      customers: "clients",
      unit: "a job",
      per: "a job",
      capacity: "how many jobs you can run at once before your one good site manager is on three of them",
      capacityShort: "clients you can take on",
      place: "region",
      places: "regions",
      quality: "the standard of the work, and whether it is still sound in ten years",
      brand: "whether your board is on a hoarding at a job people rate",
      service: "turning up, finishing, and still answering the phone six months later",
      turnedAway: "work you had to turn down because there was nobody to put on it",
      market: "the trade",
      rivals: "the other firms",
    },
    segments: [
      { id: "homeowners", name: "Homeowners", description: "A kitchen, an extension, a fence. Get three quotes, pick the cheapest, and tell the whole street how it went.", size: 210_000, growth: 0.03, priceSensitivity: 0.85, qualityFocus: 0.55, brandFocus: 0.35, serviceFocus: 0.6, loyalty: 0.15, referencePrice: 900 },
      { id: "developers", name: "Developers", description: "Ten jobs a year to whoever finished the last one on time. Slow to win, and they'll bring you along for the next decade.", size: 29_000, growth: 0.06, priceSensitivity: 0.5, qualityFocus: 0.8, brandFocus: 0.4, serviceFocus: 0.75, loyalty: 0.82, referencePrice: 3_800 },
      { id: "public", name: "Public sector", description: "Schools, roads, a hospital wing. A tender process longer than the build, and a blacklist that never expires.", size: 6_000, growth: 0.04, priceSensitivity: 0.45, qualityFocus: 0.85, brandFocus: 0.55, serviceFocus: 0.8, loyalty: 0.92, referencePrice: 14_000 },
    ],
    cities: [
      { id: "south_east", name: "The South East", weight: 0.27, entryCost: 1_600_000, note: "Most of the money, and most of the firms chasing it.",
        mix: { homeowners: 1, developers: 1, public: 1 } },
      { id: "midlands", name: "The Midlands", weight: 0.171, entryCost: 600_000, note: "Steady work, and buyers who remember who turned up.",
        mix: { homeowners: 1.022, developers: 1.022, public: 0.978 } },
      { id: "north_west", name: "The North West", weight: 0.153, entryCost: 520_000, note: "Regeneration money, with a decade of it still to spend.",
        mix: { homeowners: 0.978, developers: 1.067, public: 1.045 } },
      { id: "scotland", name: "Scotland", weight: 0.126, entryCost: 450_000, note: "Its own procurement rules, and a shorter building season.",
        mix: { homeowners: 0.978, developers: 0.978, public: 1.113 } },
      { id: "yorkshire", name: "Yorkshire", weight: 0.108, entryCost: 400_000, note: "Relationships here are measured in decades, not tenders.",
        mix: { homeowners: 1.045, developers: 0.978, public: 1.0 } },
      { id: "wales", name: "Wales", weight: 0.072, entryCost: 280_000, note: "Cheapest entry, smallest jobs, and very little competition.",
        mix: { homeowners: 1.067, developers: 0.932, public: 1.045 } },
      { id: "south_west", name: "The South West", weight: 0.035, entryCost: 120_000, note: "Extensions, conversions and second homes, all of it private.",
        mix: { homeowners: 1.135, developers: 0.955, public: 0.887 } },
      { id: "east_anglia", name: "East Anglia", weight: 0.03, entryCost: 100_000, note: "New estates on farmland, and developers who repeat the same plot.",
        mix: { homeowners: 0.955, developers: 1.135, public: 0.932 } },
      { id: "north_east", name: "The North East", weight: 0.02, entryCost: 70_000, note: "Public money is most of the pipeline, and it pays slowly.",
        mix: { homeowners: 0.955, developers: 0.955, public: 1.157 } },
      { id: "northern_ireland", name: "Northern Ireland", weight: 0.015, entryCost: 50_000, note: "Small, close-knit, and framework contracts decide everything.",
        mix: { homeowners: 0.978, developers: 0.955, public: 1.135 } },
    ],
    incumbents: [
      {
        id: "inc_hartwell", name: "Hartwell Builders", posture: "fortress", startingShare: 0.32, quality: 73, brand: 78, service: 76, priceIndex: 1.22,
        persona: {
          tagline: "Hartwell. Since 1931.",
          boss: "Third-generation chairman Edward Hartwell, who knows every developer in the South East by their first name and their father\u2019s.",
          character: "Hartwell does not really bid for work, it gets asked. Ninety years of finishing on time has bought it a relationship with every serious developer in the country, and those relationships are worth more than any tender. It is expensive, unhurried, and utterly immovable on quality — it walked away from a large job last year over a specification and made sure the industry heard about it.",
          known: "Developers call them first",
          knock: "They will not touch a homeowner\u2019s kitchen and they price themselves out of anything competitive. Ninety per cent of the jobs in this market are ones Hartwell does not want.",
          voice: "Bidding is for firms nobody has heard of. We have a diary.",
        },
      },
      {
        id: "inc_bricktop", name: "Bricktop", posture: "brawler", startingShare: 0.26, quality: 52, brand: 61, service: 44, priceIndex: 0.73,
        persona: {
          tagline: "We will beat any written quote.",
          boss: "Sean Rafferty, who came up on the tools, still drives to sites at six, and will take a job at a loss to keep a rival off it.",
          character: "Bricktop wins on price and makes it back on variations. The initial quote is always the cheapest on the table and the final invoice rarely is, which homeowners find out one at a time and developers found out years ago. The work is adequate, the programme slips, and the firm is ferociously hard to compete with on anything a customer decides in an afternoon.",
          known: "Always the cheapest quote",
          knock: "The final bill never matches it. Every repeat client they have ever had is now somebody else\u2019s repeat client.",
          voice: "Show me their number. I will do it for less and I will start Monday.",
        },
      },
      {
        id: "inc_ironwood", name: "Ironwood", posture: "innovator", startingShare: 0.2, quality: 84, brand: 55, service: 69, priceIndex: 1.3,
        persona: {
          tagline: "Built in a factory. Assembled on site.",
          boss: "Priya Raghunathan, a structural engineer who says the industry has not had a real idea since the tower crane.",
          character: "Ironwood builds most of the building in a shed in Doncaster and bolts it together on site in a fortnight. When it works — and on the public-sector jobs it works beautifully — nothing else comes close on programme or on finish. It costs more, it needs the client to accept a design they cannot change halfway through, and half the trade still thinks it is a fad.",
          known: "Finishes in half the time",
          knock: "Their method needs a client who will decide everything up front. Homeowners never do, and homeowners are most of the market.",
          voice: "They are still building things outdoors, in this country, in February. Extraordinary.",
        },
      },
      {
        id: "inc_northgate", name: "Northgate", posture: "coaster", startingShare: 0.12, quality: 47, brand: 60, service: 42, priceIndex: 0.95,
        persona: {
          tagline: "Regional contractors since 1978.",
          boss: "Two directors in their sixties who have stopped taking on anything that needs a new hire.",
          character: "Northgate has a framework agreement with two councils and that is the whole business. The work comes in, the work goes out, the margin is thin and predictable, and nobody has looked for a new client in six years. The good people left for Hartwell. What is left turns up, does it, and goes home.",
          known: "A framework nobody can take",
          knock: "Outside those two councils they do not exist. There is no sales function, no marketing, and no plan for what happens when the framework is re-tendered.",
          voice: "We have enough on, thanks.",
        },
      },
    ],
  },
  {
    id: "project_saas",
    penetration: { north_america: 1.5, europe: 1.2, asia: 0.8, south_america: 0.7, africa: 0.4 },
    name: "Project management software",
    premise: "Software for people who need to know who's doing what. Free for five users, priced per seat, and every company already has three of them.",
    baseUnitCost: 11,
    innovationPace: 1.25,
        workforce: [
      { id: "engineers", name: "engineers", one: "an engineer", does: "product", pay: 1.8, share: 0.45 },
      { id: "success", name: "customer success", one: "a success manager", does: "service", pay: 1.0, share: 0.3 },
      { id: "infra", name: "infrastructure", one: "an infrastructure engineer", does: "room", pay: 1.6, share: 0.25 },
    ],
    voice: {
      customer: "seat",
      customers: "seats",
      unit: "a seat",
      per: "a seat, a month",
      capacity: "how many seats you can onboard and support at once before the roadmap disappears under the support queue",
      capacityShort: "seats you can carry",
      place: "region",
      places: "regions",
      quality: "whether it holds up on a Monday morning with two hundred people in it",
      brand: "whether you are on the shortlist before anyone has seen a demo",
      service: "onboarding, migrations, and how fast the security questionnaire comes back",
      turnedAway: "deals lost because you could not get them live in time",
      market: "the category",
      rivals: "the other tools",
    },
    segments: [
      { id: "startups", name: "Startups", description: "Sign up on the free tier, invite the whole team, and leave the week they hire an ops person who prefers the other one.", size: 4_220_000, growth: 0.07, priceSensitivity: 0.8, qualityFocus: 0.5, brandFocus: 0.4, serviceFocus: 0.3, loyalty: 0.16, referencePrice: 55 },
      { id: "midsize", name: "Mid-size teams", description: "Two hundred seats and four years of project history. Nobody wants to be the person who migrated it.", size: 1_440_000, growth: 0.06, priceSensitivity: 0.4, qualityFocus: 0.72, brandFocus: 0.35, serviceFocus: 0.7, loyalty: 0.8, referencePrice: 95 },
      { id: "enterprise", name: "Enterprise", description: "A security questionnaire, a procurement process, and a three-year contract. Eighteen months to win, and they'll renew without reading it.", size: 290_000, growth: 0.05, priceSensitivity: 0.3, qualityFocus: 0.8, brandFocus: 0.6, serviceFocus: 0.9, loyalty: 0.93, referencePrice: 180 },
    ],
    cities: [
      { id: "north_america", name: "North America", weight: 0.297, entryCost: 1_700_000, note: "Half the money in the category, and every rival already there.",
        mix: { startups: 1, midsize: 1, enterprise: 1 } },
      { id: "uk_ireland", name: "UK and Ireland", weight: 0.153, entryCost: 520_000, note: "Where you start, and small enough to run out of quickly.",
        mix: { startups: 1.067, midsize: 1.022, enterprise: 0.955 } },
      { id: "dach", name: "Germany, Austria and Switzerland", weight: 0.144, entryCost: 720_000, note: "Slow to sign, then impossible to shift. The data rules are the work.",
        mix: { startups: 0.91, midsize: 1.022, enterprise: 1.135 } },
      { id: "nordics", name: "The Nordics", weight: 0.108, entryCost: 480_000, note: "Small, rich, and they buy software properly.",
        mix: { startups: 1.0, midsize: 1.067, enterprise: 1.0 } },
      { id: "anz", name: "Australia and New Zealand", weight: 0.108, entryCost: 460_000, note: "Far away, English-speaking, and nobody is serving it well.",
        mix: { startups: 1.022, midsize: 1.067, enterprise: 0.955 } },
      { id: "benelux", name: "The Benelux", weight: 0.09, entryCost: 380_000, note: "The cheapest way onto the continent.",
        mix: { startups: 1.0, midsize: 1.067, enterprise: 0.978 } },
      { id: "france", name: "France", weight: 0.035, entryCost: 140_000, note: "Buys in French, from a French entity, or not at all.",
        mix: { startups: 0.932, midsize: 1.022, enterprise: 1.09 } },
      { id: "southern_europe", name: "Southern Europe", weight: 0.03, entryCost: 120_000, note: "Cheap to reach, slow to pay, and full of teams outgrowing spreadsheets.",
        mix: { startups: 1.09, midsize: 1.045, enterprise: 0.887 } },
      { id: "japan", name: "Japan", weight: 0.02, entryCost: 80_000, note: "The longest sales cycle in the world, and customers who never leave.",
        mix: { startups: 0.865, midsize: 0.978, enterprise: 1.202 } },
      { id: "latam", name: "Latin America", weight: 0.015, entryCost: 60_000, note: "Fast-growing, price-sensitive, and almost no local competition.",
        mix: { startups: 1.157, midsize: 0.978, enterprise: 0.865 } },
    ],
    incumbents: [
      {
        id: "inc_taskwell", name: "Taskwell", posture: "fortress", startingShare: 0.35, quality: 72, brand: 84, service: 70, priceIndex: 1.18,
        persona: {
          tagline: "The standard.",
          boss: "CEO Martin Oyelaran, who has said in three consecutive earnings calls that the company\u2019s job is to be boring.",
          character: "Taskwell is what a company buys when nobody wants to defend the choice. It is fine at everything, best at nothing, and has spent eight years making itself impossible to remove: the integrations, the audit logs, the four years of project history, the fact that IT already approved it. Its renewal rate is the highest in the category and almost none of it is affection.",
          known: "Nobody ever got fired for buying it",
          knock: "Nobody likes using it. Every team that has a choice picks something else, and the free tier is where rivals have been quietly eating them for years.",
          voice: "New tools are exciting. Migrations are not. We will be here when they have finished being exciting.",
        },
      },
      {
        id: "inc_gridline", name: "Gridline", posture: "brawler", startingShare: 0.27, quality: 58, brand: 66, service: 45, priceIndex: 0.75,
        persona: {
          tagline: "Every feature. Half the price.",
          boss: "Co-founder Anya Petrosyan, who ships a competitor\u2019s feature within six weeks as a matter of policy and says so openly.",
          character: "Gridline does everything the others do, badly, for a third of the money, and that is enough for an enormous number of teams. Its pricing page exists to sit next to somebody else\u2019s. It wins every deal that comes down to a spreadsheet and loses every one that comes down to a trial, and it has structured the sales process so that fewer of them come down to a trial.",
          known: "A feature list nobody can match",
          knock: "None of it is finished. Anybody who actually uses it for a quarter starts looking, which is why they churn at three times the category average.",
          voice: "We will have that feature by the end of the month, and ours will be free.",
        },
      },
      {
        id: "inc_boardroom", name: "Boardroom", posture: "innovator", startingShare: 0.17, quality: 86, brand: 56, service: 66, priceIndex: 1.33,
        persona: {
          tagline: "For teams who already know how they work.",
          boss: "Founder Tomas Lindqvist, who refuses to build a Gantt chart and has written two thousand words on why.",
          character: "Boardroom is a genuinely new idea about how work is tracked, and the teams who take to it become evangelists — they will not use anything else, and they bring it with them when they change jobs. It is also opinionated to the point of rudeness, has a fortnight of learning curve, and cannot be bought by a procurement department that wants a feature comparison.",
          known: "The teams who switch never switch back",
          knock: "It will not do what enterprise buyers ask for, on principle. That is a quarter of a billion in seats they have decided not to sell to.",
          voice: "They have built the same product four times. We would rather build a different one once.",
        },
      },
      {
        id: "inc_plannr", name: "Plannr", posture: "coaster", startingShare: 0.11, quality: 46, brand: 63, service: 39, priceIndex: 0.94,
        persona: {
          tagline: "Simple project management.",
          boss: "Acquired four years ago. It is a line item in a portfolio and the roadmap is approved annually by somebody who has not used it.",
          character: "Plannr was lovely in 2017 and has been on maintenance ever since. It still has a lot of seats, because a lot of companies bought it and nobody has proposed moving, and it still gets recommended by people describing the version they used six years ago. Support is a help centre. There is no roadmap anybody outside could name.",
          known: "Seats that came in years ago and stayed",
          knock: "There is nobody home. Those seats are sitting there waiting for one person on each team to suggest an alternative.",
          voice: "Plannr continues to serve thousands of teams worldwide.",
        },
      },
    ],
  },
  {
    id: "mmos",
    // The one market where Asia is the home of the industry rather than an export.
    penetration: { asia: 1.6, north_america: 1.1, europe: 1.1, africa: 0.4, oceania: 0.9 },
    name: "MMOs",
    premise: "Five years and fifty million to make, and the players will judge it on the first weekend. Nobody plays an MMO alone, which is the whole point and the whole problem.",
    baseUnitCost: 4,
    innovationPace: 1.5,
        workforce: [
      { id: "devs", name: "game developers", one: "a developer", does: "product", pay: 1.7, share: 0.45 },
      { id: "gm", name: "game masters", one: "a game master", does: "service", pay: 0.8, share: 0.3 },
      { id: "ops", name: "server operations", one: "an operations engineer", does: "room", pay: 1.5, share: 0.25 },
    ],
    voice: {
      customer: "player",
      customers: "players",
      unit: "a month of subscription",
      per: "a month",
      capacity: "how many players you can hold on a launch weekend before the queue becomes the story",
      capacityShort: "players your servers hold",
      place: "region",
      places: "regions",
      quality: "whether the endgame is worth the grind to reach it",
      brand: "whether the trailer gets covered or ignored",
      service: "server stability, support tickets, and whether anybody reads the forums",
      turnedAway: "players who sat in a login queue and asked for a refund",
      market: "the genre",
      rivals: "the other worlds",
    },
    segments: [
      { id: "tourists", name: "Launch tourists", description: "Buy every big release, hit level twenty, quit the moment the login queue's gone.", size: 4_670_000, growth: 0.04, priceSensitivity: 0.75, qualityFocus: 0.6, brandFocus: 0.65, serviceFocus: 0.2, loyalty: 0.12, referencePrice: 45 },
      { id: "guilds", name: "Guild members", description: "Play because their friends play. You can't take one; you have to take all forty at once.", size: 1_000_000, growth: 0.05, priceSensitivity: 0.35, qualityFocus: 0.75, brandFocus: 0.3, serviceFocus: 0.6, loyalty: 0.88, referencePrice: 130 },
      { id: "veterans", name: "Veterans", description: "Ten years, six alts, a subscription they've never cancelled. Complain constantly, and would sooner die than leave.", size: 360_000, growth: 0.03, priceSensitivity: 0.2, qualityFocus: 0.7, brandFocus: 0.2, serviceFocus: 0.85, loyalty: 0.94, referencePrice: 190 },
    ],
    cities: [
      { id: "north_america", name: "North America", weight: 0.279, entryCost: 1_600_000, note: "The launch that decides whether anybody else covers you.",
        mix: { tourists: 1, guilds: 1, veterans: 1 } },
      { id: "europe", name: "Europe", weight: 0.216, entryCost: 900_000, note: "Seven languages, and a server everybody will complain about.",
        mix: { tourists: 1.0, guilds: 1.045, veterans: 1.0 } },
      { id: "korea_japan", name: "Korea and Japan", weight: 0.135, entryCost: 1_100_000, note: "Pays more per player than anywhere, and will not tolerate a bad patch.",
        mix: { tourists: 0.932, guilds: 1.045, veterans: 1.09 } },
      { id: "sea", name: "South East Asia", weight: 0.126, entryCost: 460_000, note: "Vast, mobile-first, and growing faster than anywhere else.",
        mix: { tourists: 1.135, guilds: 0.978, veterans: 0.91 } },
      { id: "latam", name: "Latin America", weight: 0.081, entryCost: 340_000, note: "Cheap to enter, loyal once you are in, and almost nobody localising.",
        mix: { tourists: 1.067, guilds: 1.022, veterans: 0.932 } },
      { id: "oceania", name: "Oceania", weight: 0.063, entryCost: 280_000, note: "Small, and they will forgive almost anything except lag.",
        mix: { tourists: 1.0, guilds: 1.022, veterans: 1.022 } },
      { id: "china", name: "Greater China", weight: 0.035, entryCost: 140_000, note: "A licence, a partner, and the largest guild scene on earth.",
        mix: { tourists: 0.955, guilds: 1.135, veterans: 0.978 } },
      { id: "russia_cis", name: "Russia and the CIS", weight: 0.03, entryCost: 120_000, note: "Hardcore, price-sensitive, and it plays what nobody else will.",
        mix: { tourists: 0.932, guilds: 1.067, veterans: 1.067 } },
      { id: "middle_east", name: "The Middle East", weight: 0.02, entryCost: 80_000, note: "New money, new servers, and a tournament scene being built from nothing.",
        mix: { tourists: 1.09, guilds: 1.045, veterans: 0.91 } },
      { id: "india", name: "India", weight: 0.015, entryCost: 60_000, note: "Phones, free-to-play, and a generation arriving all at once.",
        mix: { tourists: 1.157, guilds: 0.978, veterans: 0.865 } },
    ],
    incumbents: [
      {
        id: "inc_aether", name: "Realms of Aether", posture: "fortress", startingShare: 0.41, quality: 78, brand: 89, service: 72, priceIndex: 1.15,
        persona: {
          tagline: "Eleven years. One world.",
          boss: "Game director Hana Sorensen, who has run it for seven years and is the only person alive that the veteran forums will not call a sellout.",
          character: "Aether is not a game any more, it is where several million people\u2019s friends are. Eleven years of guilds, characters and in-jokes sit inside it, and none of that can be exported, which is a moat no amount of money can dig. It patches on a schedule you could set a calendar by, runs the best support in the genre, and has not had a genuinely new idea since its second expansion.",
          known: "Everyone\u2019s friends are already in it",
          knock: "It is eleven years old and it looks it. The tourists it pulls in every expansion take one look at the interface and leave before the free trial is up.",
          voice: "Launches are easy. Come back and talk to us about year four.",
        },
      },
      {
        id: "inc_starforge", name: "Starforge Online", posture: "innovator", startingShare: 0.24, quality: 88, brand: 61, service: 65, priceIndex: 1.3,
        persona: {
          tagline: "A galaxy that remembers what you did.",
          boss: "Studio head Dmitri Vance, who missed two announced launch dates rather than ship something he had seen play badly.",
          character: "Starforge is the most ambitious thing running: a persistent universe where player actions genuinely change the map, and when a season of it goes well it is the best experience in the genre by a wide margin. It is also enormously expensive to operate, ships late, and has a first hour so complicated that most of the people it attracts never see the good part.",
          known: "The best thing in the genre when it works",
          knock: "Nobody can get through the first three hours. They lose most of a launch audience before the game starts being itself.",
          voice: "We could have shipped it last year. You would not have played it in two.",
        },
      },
      {
        id: "inc_dominion", name: "Dominion", posture: "brawler", startingShare: 0.14, quality: 57, brand: 63, service: 44, priceIndex: 0.74,
        persona: {
          tagline: "Free to play. Always was.",
          boss: "A publisher-side operator named Vic Crane whose title is Head of Monetisation and whose actual job is the whole company.",
          character: "Dominion is free, enormous, and relentlessly monetised — every season is an event, every event is a battle pass, and the whole thing is tuned by a live-ops team that reads the numbers daily and adjusts before anyone notices. It undercuts every subscription in the genre by the simple method of not having one, and it will drop a season on top of anybody else\u2019s launch weekend on purpose.",
          known: "Free, and always in the conversation",
          knock: "The guilds despise it. Nothing in it is designed for forty friends who want to play together for three years, and that is where the money actually is.",
          voice: "Charging people up front. In this decade. Bold.",
        },
      },
      {
        id: "inc_emberfall", name: "Emberfall", posture: "coaster", startingShare: 0.11, quality: 45, brand: 58, service: 38, priceIndex: 0.96,
        persona: {
          tagline: "The classic fantasy MMO.",
          boss: "A live team of eleven, down from ninety. The last game director left and was not replaced.",
          character: "Emberfall had six good years and has been in maintenance mode for four. The veterans are still there — they have a decade in it and nowhere else to put it — and they subsidise a game that gets one small content patch a year and a seasonal event that is the same seasonal event. Everybody involved knows, and nobody says it out loud.",
          known: "Veterans who will never cancel",
          knock: "Nothing new has shipped in four years. Those veterans are the most valuable players in the genre and they are one good launch away from being someone else\u2019s.",
          voice: "The servers are still up. That is more than most can say.",
        },
      },
    ],
  },
];

export const nicheById = (id: string): Niche | undefined => NICHES.find((n) => n.id === id);
