/** Generated by script/build-logo-assets.mjs — positions are percentages of the artboard; dir is the unit vector each bolt shoots along. */
export const LOGO_LAYOUT = {
  "aspect": 0.6451612903225806,
  "tower": {
    "src": "/brand/tower.png",
    "left": 8,
    "top": 2.9,
    "width": 66,
    "height": 96.45
  },
  "bolts": [
    {
      "id": "topMid",
      "src": "/brand/bolt-topMid.png",
      "left": 45.54,
      "top": -0.25,
      "width": 12.92,
      "height": 23.65,
      "dirX": 0.09,
      "dirY": -0.996
    },
    {
      "id": "topLeft",
      "src": "/brand/bolt-topLeft.png",
      "left": 3.24,
      "top": 8.25,
      "width": 34.07,
      "height": 14.86,
      "dirX": -0.787,
      "dirY": -0.617
    },
    {
      "id": "topRight",
      "src": "/brand/bolt-topRight.png",
      "left": 61.28,
      "top": 10.67,
      "width": 36.66,
      "height": 14.4,
      "dirX": 0.812,
      "dirY": -0.584
    },
    {
      "id": "midLeft",
      "src": "/brand/bolt-midLeft.png",
      "left": 0.65,
      "top": 22.5,
      "width": 30.31,
      "height": 9.85,
      "dirX": -0.985,
      "dirY": -0.171
    },
    {
      "id": "bottomLeft",
      "src": "/brand/bolt-bottomLeft.png",
      "left": 0.65,
      "top": 32.35,
      "width": 29.38,
      "height": 5.61,
      "dirX": -0.987,
      "dirY": 0.163
    },
    {
      "id": "midRight",
      "src": "/brand/bolt-midRight.png",
      "left": 67.86,
      "top": 27.35,
      "width": 34.31,
      "height": 5.15,
      "dirX": 0.998,
      "dirY": -0.067
    },
    {
      "id": "bottomRight",
      "src": "/brand/bolt-bottomRight.png",
      "left": 69.5,
      "top": 32.81,
      "width": 28.9,
      "height": 8.95,
      "dirX": 0.972,
      "dirY": 0.236
    }
  ]
} as const;
