/**
 * The certificate, which somebody prints and keeps.
 *
 * It carries four facts that have to be exactly right — a name, a believer
 * number, a project, and a date — on a document whose whole point is being
 * framed. That is why it is drawn rather than generated by an image model: a
 * model misspells names and invents digits, and nobody proofreads a reward.
 *
 * What can be asserted here is the SVG, which is the certificate before it is a
 * picture. Two kinds of thing are worth holding:
 *
 *   - **It renders at all.** The text is converted to outlines by a library that
 *     emits the literal string "NaN" for some glyph and size combinations, and an
 *     SVG containing NaN does not fail — the renderer silently stops drawing at
 *     that point. That is how a garment came out reading "s" instead of "since
 *     March 2026", and a certificate would fail the same silent way.
 *   - **The date.** It was wrong the first time it was drawn: `toLocaleDateString`
 *     in the server's own zone turns a pledge stored at midnight UTC into the day
 *     before, anywhere west of Greenwich. Nobody would have queried it. It is
 *     simply the wrong date on something somebody keeps.
 */
import { describe, it, expect } from "vitest";
import { BADGE_LEVELS, badgeLevelForAmount } from "@shared/backing";
import { CERT_HEIGHT, CERT_WIDTH, buildCertificateSvg, certificateDate } from "../../server/certificate-render";

const base = {
  backerName: "Ada Marchetti",
  projectTitle: "SparkTower",
  believerNumber: 47,
  amountCents: 3_500,
  backedAt: new Date("2026-03-09T00:00:00Z"),
  creatorName: "Hunter Damsgard",
};

/** Text is drawn as outlines, so nothing on the certificate is searchable as a word. */
const draw = (over: Partial<typeof base> = {}) => buildCertificateSvg({ ...base, ...over });

describe("the date on a certificate", () => {
  /*
   * The bug, pinned. A pledge stored at midnight UTC renders as the previous day
   * in every negative-offset zone, which is most of the Americas — and the server
   * that draws it has no business having an opinion about the backer's timezone
   * anyway.
   */
  it("is the UTC date, whatever zone the server is in", () => {
    expect(certificateDate(new Date("2026-03-09T00:00:00Z"))).toBe("9 March 2026");
    expect(certificateDate(new Date("2026-11-30T23:30:00Z"))).toBe("30 November 2026");
    expect(certificateDate(new Date("2026-01-01T00:00:00Z"))).toBe("1 January 2026");
  });

  it("is spelled out, because a certificate is not a receipt", () => {
    const text = certificateDate(new Date("2026-03-09T00:00:00Z"));
    expect(text).toContain("March");
    expect(text).not.toMatch(/\d{2}\/\d{2}/);
  });
});

describe("drawing a certificate", () => {
  it("produces a page of the size it claims", () => {
    const svg = draw();
    expect(svg.startsWith("<svg")).toBe(true);
    expect(svg).toContain(`width="${CERT_WIDTH}"`);
    expect(svg).toContain(`height="${CERT_HEIGHT}"`);
    /* 11in x 8.5in at 300dpi — a Letter sheet, landscape. */
    expect(CERT_WIDTH / 300).toBeCloseTo(11, 5);
    expect(CERT_HEIGHT / 300).toBeCloseTo(8.5, 5);
  });

  /*
   * The silent failure this whole renderer is shaped around. A path containing
   * NaN does not throw; the rasteriser just stops drawing, and the certificate
   * comes out missing a word nobody notices until it is on a wall.
   */
  it("never emits a non-finite coordinate, for any name or any size", () => {
    const names = [
      "Ada Marchetti", "Bartholomew Fitzwilliam-Harrington", "Jo", "X",
      "Zoë Ferreira", "O'Brien", "李明", "Anna-Maria de la Cruz",
    ];
    for (const backerName of names) {
      for (const amountCents of [500, 1_500, 3_500, 7_500, 250_000]) {
        const svg = draw({ backerName, amountCents });
        expect(svg, `${backerName} @ ${amountCents}`).not.toContain("NaN");
        expect(svg, `${backerName} @ ${amountCents}`).not.toContain("Infinity");
        expect(svg, `${backerName} @ ${amountCents}`).not.toContain("undefined");
      }
    }
  });

  it("draws something for every field, not an empty page", () => {
    const svg = draw();
    /* Each glyph is one path; a page with the words missing has almost none. */
    const glyphs = (svg.match(/<path /g) || []).length;
    expect(glyphs, "the words are drawn as outlines").toBeGreaterThan(80);
    const ornament = (svg.match(/<polyline /g) || []).length;
    expect(ornament, "the woven border and the rosettes").toBeGreaterThan(8);
  });

  /* The metal is the only thing distinguishing a $5 certificate from a $75 one. */
  it("is struck in the metal the pledge earned", () => {
    for (const level of BADGE_LEVELS) {
      const svg = draw({ amountCents: level.minCents });
      expect(badgeLevelForAmount(level.minCents).key).toBe(level.key);
      expect(svg, `${level.key} should ink the page in ${level.hex}`).toContain(level.hex);
    }
    /* And two levels really do differ, rather than all resolving to the same ink. */
    expect(draw({ amountCents: 500 })).not.toBe(draw({ amountCents: 7_500 }));
  });

  /*
   * The border is seeded from the content, so one backer's weave is their own —
   * and redrawing the same certificate gives the same file, which is what lets it
   * be generated on request rather than stored.
   */
  it("is identical when drawn twice, and different between backers", () => {
    expect(draw()).toBe(draw());
    expect(draw({ believerNumber: 48 })).not.toBe(draw({ believerNumber: 47 }));
    expect(draw({ projectTitle: "Kettle & Fern" })).not.toBe(draw());
  });

  it("copes with a backing that never got a believer number", () => {
    const svg = draw({ believerNumber: null });
    expect(svg).not.toContain("NaN");
    expect(svg).not.toContain("null");
    expect((svg.match(/<path /g) || []).length).toBeGreaterThan(80);
  });

  it("copes with the names people actually have, including none at all", () => {
    for (const backerName of ["", "   ", "A"]) {
      const svg = draw({ backerName });
      expect(svg, JSON.stringify(backerName)).not.toContain("NaN");
      expect((svg.match(/<path /g) || []).length).toBeGreaterThan(60);
    }
  });

  /*
   * A long name shrinks to fit rather than running off the page. The alternative
   * is a certificate with half a surname on it, which is worse than a small one.
   */
  it("shrinks a long name instead of overflowing the page", () => {
    const long = draw({ backerName: "Bartholomew Fitzwilliam-Harrington the Third" });
    const short = draw({ backerName: "Jo" });
    /*
     * Glyph transforms only. The signature is skewed about its own origin, which
     * is written as `translate(x y) skewX(..) translate(-x -y)` — so a regex over
     * every transform on the page finds that compensating -2630 and reads it as a
     * letter two thousand pixels off the left edge. It is not; it is the pivot.
     */
    const xs = (svg: string) =>
      [...svg.matchAll(/<path d="[^"]*" transform="translate\((-?[\d.]+) /g)].map((m) => Number(m[1]));
    expect(xs(long).length, "there are glyphs to check").toBeGreaterThan(40);
    expect(Math.min(...xs(long)), "nothing is drawn off the left edge").toBeGreaterThan(-50);
    expect(Math.max(...xs(long)), "nor off the right").toBeLessThan(CERT_WIDTH + 50);
    expect(long).not.toBe(short);
  });

  it("says the creator signed it, and names them", () => {
    const svg = draw({ creatorName: "Zara Ferreira" });
    /* The signature is slanted — that transform is the only skew on the page. */
    expect(svg, "the signature is set at an angle").toContain("skewX");
    expect(draw({ creatorName: "Zara Ferreira" })).not.toBe(draw({ creatorName: "Someone Else" }));
  });
});
